export const ACTIONS={
    GET_SONGS:"GET_SONGS",
    GET_ALBUMS:"GET_ALBUMS",
    //
    DELETE_SONG:"DELETE_SONG",
    ADD_SONG:"ADD_SONG",
    // DELETE_SONG_REQUEST:"DELETE_SONG_REQUEST",

    // NO OF SONGS ALBUMS GENRES AND ARTISTS
    GET_NO_OF_ALBUMS:"GET_NO_OF_ALBUMS",
    GET_NO_OF_SONGS:"GET_NO_OF_SONGS",
    GET_NO_OF_ARTISTS:"GET_NO_OF_ARTISTS",
    GET_NO_OF_GENRES:"GET_NO_OF_GENRES",
    // statics
    GET_ALBUM_STATICS:"GET_ALBUM_STATICS",
    GET_ARTIST_STATICS:"GET_ARTIST_STATICS",
    GET_GENRE_STATICS:"GET_GENRE_STATICS",

    // home state actions
    OPEN_EDIT_DIALOGUE:"OPEN_EDIT_DIALOGUE",
    OPEN_DELETE_DIALOGUE:"OPEN_DELETE_DIALOGUE",

    // EDIT PAGE 
    UPDATE_SONG:"UPDATE_SONG",
    FETCH_SONG:"FETCH_SONG"
}
export const SET_ACTIONS={
    SET_SONG:"SET_SONGS",
    SET_ALBUMS:"SET_ALBUMS",
    
    // set update song 
    SET_DELETE_SONG:"SET_DELETE_SONG",
    SET_ADD_SONG:"SET_ADD_SONG",
    SET_DELETE_SONG_REQUEST:"DELETE_SONG_REQUEST",
    SET_UPDATE_SONG_REQUEST:"UPDATE_SONG_REQUEST",
    SET_ADD_SONG_REQUEST:"ADD_SONG_REQUEST",
     // NO OF SONGS ALBUMS GENRES AND ARTISTS
    SET_NO_OF_ALBUMS:"SET_NO_OF_ALBUMS",
    SET_NO_OF_SONGS:"SET_NO_OF_SONGS",
    SET_NO_OF_ARTISTS:"SET_NO_OF_ARTISTS",
    SET_NO_OF_GENRES:"SET_NO_OF_GENRES",
    // statics 
    // statics
    SET_ALBUM_STATICS:"SET_ALBUM_STATICS",
    SET_ARTIST_STATICS:"SET_ARTIST_STATICS",
    SET_GENRE_STATICS:"SET_GENRE_STATICS",

    // EDIT 
    SET_UPDATE_SONG:"SET_UPDATE_SONG",
    SET_FETCH_SONG:"SET_FETCH_SONG"
}